# Generated by Django 3.1.6 on 2021-02-08 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_active',
            new_name='is_staff',
        ),
    ]
